from document_utils import generate_docx, generate_pdf


title = "LegalEase Test Document"

content = [
    {
        "heading": "Introduction",
        "text": "This is a test document generated by the LegalEase system."
    },
    {
        "heading": "Purpose",
        "text": "This test checks whether LegalEase can create DOCX and PDF files."
    },
    {
        "heading": "Conclusion",
        "text": "The document generation module is working correctly."
    }
]


docx_file = generate_docx(title, content)
pdf_file = generate_pdf(title, content)

print("DOCX created:", docx_file)
print("PDF created:", pdf_file)